import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Zap } from "lucide-react";

export default function Home() {
  return (
    <main className="flex flex-col items-center justify-center min-h-screen p-8 bg-background">
      <div className="text-center space-y-8">
        <div className="flex flex-col items-center space-y-4">
          <div className="p-4 bg-primary/10 rounded-full">
            <Zap className="w-16 h-16 text-primary" />
          </div>
          <h1 className="text-5xl md:text-7xl font-bold font-headline text-primary tracking-tighter">
            Neon Maze AI
          </h1>
        </div>
        <p className="text-lg md:text-xl max-w-2xl text-muted-foreground">
          An electrifying puzzle adventure. Navigate glowing labyrinths generated by AI. How fast can you escape?
        </p>
        <div className="flex flex-col sm:flex-row gap-4 justify-center pt-4">
          <Button asChild size="lg" className="font-bold text-lg w-full sm:w-40 transition-transform hover:scale-105">
            <Link href="/play/easy">Easy</Link>
          </Button>
          <Button asChild size="lg" variant="outline" className="font-bold text-lg w-full sm:w-40 border-primary text-primary hover:bg-primary/10 hover:text-primary transition-transform hover:scale-105">
            <Link href="/play/medium">Medium</Link>
          </Button>
          <Button asChild size="lg" className="font-bold text-lg w-full sm:w-40 bg-accent hover:bg-accent/90 text-accent-foreground transition-transform hover:scale-105">
            <Link href="/play/hard">Hard</Link>
          </Button>
        </div>
      </div>
    </main>
  );
}
