import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Search } from "lucide-react";

export default function Home() {
  return (
    <main className="flex flex-col items-center justify-center min-h-screen p-8 bg-background">
      <div className="text-center space-y-8">
        <div className="flex flex-col items-center space-y-4">
          <div className="p-4 bg-primary/10 rounded-full">
            <Search className="w-16 h-16 text-primary" />
          </div>
          <h1 className="text-5xl md:text-7xl font-bold font-headline text-primary tracking-tighter">
            AI Word Search
          </h1>
        </div>
        <p className="text-lg md:text-xl max-w-2xl text-muted-foreground">
          A classic word search puzzle, generated by AI. Find all the hidden words.
        </p>
        <div className="flex flex-col sm:flex-row gap-4 justify-center pt-4">
          <Button asChild size="lg" className="font-bold text-lg w-full sm:w-48 transition-transform hover:scale-105">
            <Link href="/play/word-search">Start Searching</Link>
          </Button>
        </div>
      </div>
    </main>
  );
}
